// Copies RDKit.js + OpenChemLib resources into public/ and bundles the chemistry worker (IIFE).
import { build } from 'esbuild';
import { copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const findPkg = (name) => {
  for (let dir = root; dir !== path.dirname(dir); dir = path.dirname(dir)) {
    const p = path.join(dir, 'node_modules', name);
    if (existsSync(path.join(p, 'package.json'))) return p;
  }
  throw new Error(`Cannot find ${name}`);
};
const rdkitDir = findPkg('@rdkit/rdkit');
const oclDir = findPkg('openchemlib');

mkdirSync(path.join(root, 'public/rdkit'), { recursive: true });
mkdirSync(path.join(root, 'public/ocl'), { recursive: true });
mkdirSync(path.join(root, 'public/workers'), { recursive: true });
for (const f of ['RDKit_minimal.js', 'RDKit_minimal.wasm']) copyFileSync(path.join(rdkitDir, 'dist', f), path.join(root, 'public/rdkit', f));
copyFileSync(path.join(oclDir, 'dist/resources.json'), path.join(root, 'public/ocl/resources.json'));

const watch = process.argv.includes('--watch');
const opts = {
  entryPoints: [path.join(root, 'worker/chem.worker.ts')],
  outfile: path.join(root, 'public/workers/chem.worker.js'),
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  sourcemap: false,
  minify: !watch,
  logLevel: 'info',
  define: { 'process.env.NODE_ENV': '"production"' },
};
if (watch) {
  const { context } = await import('esbuild');
  const ctx = await context(opts);
  await ctx.watch();
} else {
  await build(opts);
}
// Content hash for cache-busting the worker URL (browser cache + service worker).
const hash = createHash('sha1').update(readFileSync(opts.outfile)).digest('hex').slice(0, 10);
const versionFile = path.join(root, 'src/lib/asset-version.ts');
const body = `// Generated by scripts/build-assets.mjs — do not edit.\nexport const WORKER_VERSION = '${watch ? 'dev' : hash}';\n`;
if (!existsSync(versionFile) || readFileSync(versionFile, 'utf8') !== body) writeFileSync(versionFile, body);
console.log('assets ready', existsSync(opts.outfile), watch ? '' : hash);
