/**
 * Course list of accepted common (trivial) names (spec §4 "Accepted common name").
 * Matched structurally (constitution + stereo where given), never by string.
 */
export interface CommonNameEntry {
  name: string;
  smiles: string;
  /** Also retained in the 2013 recommendations as the preferred IUPAC name. */
  pin?: boolean;
  note?: string;
}

export const COMMON_NAMES: CommonNameEntry[] = [
  { name: 'acetone', smiles: 'CC(C)=O' },
  { name: 'acetic acid', smiles: 'CC(=O)O', pin: true },
  { name: 'formic acid', smiles: 'OC=O', pin: true },
  { name: 'formaldehyde', smiles: 'C=O', pin: true },
  { name: 'acetaldehyde', smiles: 'CC=O' },
  { name: 'propionic acid', smiles: 'CCC(=O)O' },
  { name: 'butyric acid', smiles: 'CCCC(=O)O' },
  { name: 'valeric acid', smiles: 'CCCCC(=O)O' },
  { name: 'oxalic acid', smiles: 'OC(=O)C(=O)O', pin: true },
  { name: 'malonic acid', smiles: 'OC(=O)CC(=O)O' },
  { name: 'succinic acid', smiles: 'OC(=O)CCC(=O)O' },
  { name: 'glutaric acid', smiles: 'OC(=O)CCCC(=O)O' },
  { name: 'adipic acid', smiles: 'OC(=O)CCCCC(=O)O' },
  { name: 'acrylic acid', smiles: 'C=CC(=O)O' },
  { name: 'methacrylic acid', smiles: 'C=C(C)C(=O)O' },
  { name: 'maleic acid', smiles: 'OC(=O)/C=C\\C(=O)O' },
  { name: 'fumaric acid', smiles: 'OC(=O)/C=C/C(=O)O' },
  { name: 'lactic acid', smiles: 'CC(O)C(=O)O' },
  { name: 'pyruvic acid', smiles: 'CC(=O)C(=O)O' },
  { name: 'citric acid', smiles: 'OC(=O)CC(O)(CC(=O)O)C(=O)O' },
  { name: 'glycolic acid', smiles: 'OCC(=O)O' },
  { name: 'salicylic acid', smiles: 'OC(=O)c1ccccc1O' },
  { name: 'aspirin', smiles: 'CC(=O)Oc1ccccc1C(=O)O' },
  { name: 'ibuprofen', smiles: 'CC(C)Cc1ccc(cc1)C(C)C(=O)O' },
  { name: 'phthalic acid', smiles: 'OC(=O)c1ccccc1C(=O)O' },
  { name: 'terephthalic acid', smiles: 'OC(=O)c1ccc(cc1)C(=O)O' },
  { name: 'toluene', smiles: 'Cc1ccccc1' },
  { name: 'o-xylene', smiles: 'Cc1ccccc1C' },
  { name: 'm-xylene', smiles: 'Cc1cccc(C)c1' },
  { name: 'p-xylene', smiles: 'Cc1ccc(C)cc1' },
  { name: 'mesitylene', smiles: 'Cc1cc(C)cc(C)c1' },
  { name: 'cumene', smiles: 'CC(C)c1ccccc1' },
  { name: 'styrene', smiles: 'C=Cc1ccccc1' },
  { name: 'anisole', smiles: 'COc1ccccc1' },
  { name: 'phenol', smiles: 'Oc1ccccc1', pin: true },
  { name: 'aniline', smiles: 'Nc1ccccc1', pin: true },
  { name: 'benzaldehyde', smiles: 'O=Cc1ccccc1', pin: true },
  { name: 'benzoic acid', smiles: 'OC(=O)c1ccccc1', pin: true },
  { name: 'acetophenone', smiles: 'CC(=O)c1ccccc1' },
  { name: 'benzophenone', smiles: 'O=C(c1ccccc1)c1ccccc1' },
  { name: 'benzyl alcohol', smiles: 'OCc1ccccc1' },
  { name: 'catechol', smiles: 'Oc1ccccc1O' },
  { name: 'resorcinol', smiles: 'Oc1cccc(O)c1' },
  { name: 'hydroquinone', smiles: 'Oc1ccc(O)cc1' },
  { name: 'o-cresol', smiles: 'Cc1ccccc1O' },
  { name: 'm-cresol', smiles: 'Cc1cccc(O)c1' },
  { name: 'p-cresol', smiles: 'Cc1ccc(O)cc1' },
  { name: 'picric acid', smiles: 'Oc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]' },
  { name: 'TNT', smiles: 'Cc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]', note: '2,4,6-trinitrotoluene' },
  { name: 'vanillin', smiles: 'COc1cc(C=O)ccc1O' },
  { name: 'cinnamaldehyde', smiles: 'O=C/C=C/c1ccccc1' },
  { name: 'biphenyl', smiles: 'c1ccc(cc1)-c1ccccc1' },
  { name: 'diphenylmethane', smiles: 'C(c1ccccc1)c1ccccc1' },
  { name: 'ethylene', smiles: 'C=C' },
  { name: 'propylene', smiles: 'CC=C' },
  { name: 'isobutylene', smiles: 'CC(C)=C' },
  { name: 'isoprene', smiles: 'CC(=C)C=C' },
  { name: 'acetylene', smiles: 'C#C' },
  { name: 'isobutane', smiles: 'CC(C)C' },
  { name: 'isopentane', smiles: 'CCC(C)C' },
  { name: 'neopentane', smiles: 'CC(C)(C)C' },
  { name: 'isooctane', smiles: 'CC(C)CC(C)(C)C' },
  { name: 'ethylene glycol', smiles: 'OCCO' },
  { name: 'propylene glycol', smiles: 'CC(O)CO' },
  { name: 'glycerol', smiles: 'OCC(O)CO' },
  { name: 'diethyl ether', smiles: 'CCOCC' },
  { name: 'tetrahydrofuran', smiles: 'C1CCOC1', note: 'THF' },
  { name: 'tetrahydropyran', smiles: 'C1CCOCC1', note: 'THP' },
  { name: 'dioxane', smiles: 'C1COCCO1' },
  { name: 'ethylene oxide', smiles: 'C1CO1' },
  { name: 'propylene oxide', smiles: 'CC1CO1' },
  { name: 'chloroform', smiles: 'ClC(Cl)Cl' },
  { name: 'methylene chloride', smiles: 'ClCCl' },
  { name: 'carbon tetrachloride', smiles: 'ClC(Cl)(Cl)Cl' },
  { name: 'methyl iodide', smiles: 'CI' },
  { name: 'vinyl chloride', smiles: 'C=CCl' },
  { name: 'acetonitrile', smiles: 'CC#N', pin: true },
  { name: 'acrylonitrile', smiles: 'C=CC#N' },
  { name: 'benzonitrile', smiles: 'N#Cc1ccccc1', pin: true },
  { name: 'dimethylformamide', smiles: 'CN(C)C=O', note: 'DMF' },
  { name: 'dimethyl sulfoxide', smiles: 'CS(C)=O', note: 'DMSO' },
  { name: 'acetamide', smiles: 'CC(N)=O', pin: true },
  { name: 'acetanilide', smiles: 'CC(=O)Nc1ccccc1' },
  { name: 'acetyl chloride', smiles: 'CC(Cl)=O', pin: true },
  { name: 'acetic anhydride', smiles: 'CC(=O)OC(C)=O', pin: true },
  { name: 'ethyl acetate', smiles: 'CCOC(C)=O', pin: true },
  { name: 'methyl ethyl ketone', smiles: 'CCC(C)=O', note: 'MEK' },
  { name: 'mesityl oxide', smiles: 'CC(C)=CC(C)=O' },
  { name: 'diacetyl', smiles: 'CC(=O)C(C)=O' },
  { name: 'acetylacetone', smiles: 'CC(=O)CC(C)=O' },
  { name: 'ethyl acetoacetate', smiles: 'CCOC(=O)CC(C)=O' },
  { name: 'diethyl malonate', smiles: 'CCOC(=O)CC(=O)OCC' },
  { name: 'methyl salicylate', smiles: 'COC(=O)c1ccccc1O' },
  { name: 'isoamyl acetate', smiles: 'CC(C)CCOC(C)=O' },
  { name: 'ethanolamine', smiles: 'NCCO' },
  { name: 'triethylamine', smiles: 'CCN(CC)CC' },
  { name: 'diethylamine', smiles: 'CCNCC' },
  { name: 'trimethylamine', smiles: 'CN(C)C' },
  { name: 'benzylamine', smiles: 'NCc1ccccc1' },
  { name: 'pyridine', smiles: 'c1ccncc1', pin: true },
  { name: 'pyrrole', smiles: 'c1cc[nH]c1', pin: true },
  { name: 'furan', smiles: 'c1ccoc1', pin: true },
  { name: 'thiophene', smiles: 'c1ccsc1', pin: true },
  { name: 'naphthalene', smiles: 'c1ccc2ccccc2c1', pin: true },
  { name: 'isopropyl alcohol', smiles: 'CC(C)O' },
  { name: 'ethyl alcohol', smiles: 'CCO' },
  { name: 'methyl alcohol', smiles: 'CO' },
  { name: 'tert-butyl alcohol', smiles: 'CC(C)(C)O' },
  { name: 'glycine', smiles: 'NCC(=O)O' },
  { name: 'alanine', smiles: 'CC(N)C(=O)O' },
  { name: 'L-alanine', smiles: 'C[C@H](N)C(=O)O' },
  { name: 'caffeine', smiles: 'Cn1cnc2c1c(=O)n(C)c(=O)n2C' },
  { name: 'menthol', smiles: 'CC(C)C1CCC(C)CC1O' },
  { name: 'cholesterol', smiles: 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C' },
];
