/**
 * Resonance contributors (spec §8 "Resonance & aromaticity"). Contributors are generated by the
 * three textbook electron moves, so every contributor comes with the curved arrows that make it:
 *
 *   1. a lone pair (or anion) pushes into an adjacent π bond, whose electrons move onto the far atom
 *      (carboxylate, amide, enolate, allyl anion, phenoxide, nitro);
 *   2. a π bond shifts toward an adjacent cation / empty p orbital (allyl and benzylic cations);
 *   3. alternating π bonds shift around a six-membered ring (the two Kekulé structures of benzene).
 *
 * Atoms never move and hydrogen counts are pinned — only electrons (bond orders, charges) change.
 * Weights follow the course rules: full octets, fewest charges, negative charge on the more
 * electronegative atom.
 */
import { MolView } from './graph.ts';
import { perceiveRings } from './rings.ts';
import type { MoleculeDocument } from './types.ts';

/** Arrow endpoints are atom indices + 1 (the same addressing the mechanism library uses). */
export type ResArrowFrom = { lp: number } | { bond: [number, number] };
export type ResArrowTo = { atom: number } | { bond: [number, number] };
export interface ResArrow {
  from: ResArrowFrom;
  to: ResArrowTo;
  bend?: 1 | -1;
}

export interface Contributor {
  /** Bond orders by bond index and formal charges by atom index. */
  orders: number[];
  charges: number[];
  /** Index of the contributor these arrows start from (−1 for the input structure). */
  parent: number;
  /** Arrows drawn on the parent that produce this contributor. */
  arrows: ResArrow[];
  score: number;
  weight: 'major' | 'minor';
  notes: string[];
}

export interface ResonanceResult {
  contributors: Contributor[];
  /** True when all contributors carry the same weight (benzene, carboxylate, allyl). */
  equivalent: boolean;
  /** Atom indices whose charge or bonds differ between contributors — where the delocalization is. */
  delocalized: number[];
  /** Bond indices that change order between contributors. */
  delocalizedBonds: number[];
}

const VALENCE_E: Record<string, number> = { C: 4, N: 5, O: 6, S: 6, P: 5, F: 7, Cl: 7, Br: 7, I: 7, B: 3 };
const EN: Record<string, number> = { C: 2.55, N: 3.04, O: 3.44, S: 2.58, P: 2.19, B: 2.04 };
/** Elements that take part in moves; halogen lone pairs are left out (their donation is minor and noisy). */
const DONORS = new Set(['C', 'N', 'O', 'S']);
const ACCEPTORS = new Set(['C', 'N', 'O', 'S']);

export function resonanceContributors(doc: Pick<MoleculeDocument, 'atoms' | 'bonds'>, max = 10): ResonanceResult {
  const v = new MolView(doc);
  const n = doc.atoms.length;
  const H = doc.atoms.map((_, i) => v.totalH(i));
  const el = (i: number) => doc.atoms[i].element;
  const bondOf = (i: number, j: number) => v.bondBetween(i, j);
  const sumOrders = (orders: number[], i: number) => v.nbrBonds[i].reduce((s, b) => s + orders[b], 0);
  const lonePairs = (orders: number[], charges: number[], i: number) => {
    const ve = VALENCE_E[el(i)];
    if (ve === undefined) return 0;
    return Math.max(0, Math.floor((ve - charges[i] - sumOrders(orders, i) - H[i]) / 2));
  };
  /** Electrons around the atom (bonding pairs ×2 + lone pairs ×2); < 8 = no octet. */
  const electrons = (orders: number[], charges: number[], i: number) => 2 * (sumOrders(orders, i) + H[i]) + 2 * lonePairs(orders, charges, i);
  const emptyP = (orders: number[], charges: number[], i: number) => el(i) === 'C' && charges[i] === 1 && electrons(orders, charges, i) === 6;
  const key = (orders: number[], charges: number[]) => `${orders.join('')}|${charges.join(',')}`;

  const base = { orders: doc.bonds.map((b) => b.order as number), charges: doc.atoms.map((a) => a.formalCharge) };
  const seen = new Map<string, number>([[key(base.orders, base.charges), 0]]);
  const out: Array<Omit<Contributor, 'score' | 'weight' | 'notes'>> = [{ ...base, parent: -1, arrows: [] }];
  const rings = perceiveRings(v).rings.filter((r) => r.atoms.length === 6).map((r) => r.atoms);

  const push = (parent: number, orders: number[], charges: number[], arrows: ResArrow[]) => {
    const k = key(orders, charges);
    if (seen.has(k) || out.length >= max) return;
    // Never create an over-full atom or a double charge.
    for (let i = 0; i < n; i++) {
      if (Math.abs(charges[i]) > 1) return;
      if (VALENCE_E[el(i)] !== undefined && electrons(orders, charges, i) > 8 && el(i) !== 'S' && el(i) !== 'P') return;
    }
    // A carbocation and a carbanion in the same structure is never a drawn contributor.
    let cPlus = false;
    let cMinus = false;
    for (let i = 0; i < n; i++) {
      if (el(i) !== 'C') continue;
      if (charges[i] > 0) cPlus = true;
      if (charges[i] < 0) cMinus = true;
    }
    if (cPlus && cMinus) return;
    seen.set(k, out.length);
    out.push({ orders, charges, parent, arrows });
  };

  for (let cur = 0; cur < out.length && out.length < max; cur++) {
    const { orders, charges } = out[cur];
    for (let x = 0; x < n; x++) {
      // Move 1: lone pair on X → X–Y π, Y=Z π → Z.
      if (DONORS.has(el(x)) && lonePairs(orders, charges, x) > 0 && charges[x] <= 0) {
        for (const y of v.nbrs[x]) {
          const xy = bondOf(x, y);
          if (orders[xy] >= 3) continue;
          // Straight onto an adjacent cation.
          if (emptyP(orders, charges, y)) {
            const o = orders.slice();
            const c = charges.slice();
            o[xy] += 1;
            c[x] += 1;
            c[y] -= 1;
            push(cur, o, c, [{ from: { lp: x + 1 }, to: { bond: [x + 1, y + 1] } }]);
          }
          for (const z of v.nbrs[y]) {
            if (z === x || !ACCEPTORS.has(el(z))) continue;
            const yz = bondOf(y, z);
            if (orders[yz] < 2 || charges[z] > 0 && el(z) !== 'N') continue;
            const o = orders.slice();
            const c = charges.slice();
            o[xy] += 1;
            o[yz] -= 1;
            c[x] += 1;
            c[z] -= 1;
            push(cur, o, c, [
              { from: { lp: x + 1 }, to: { bond: [x + 1, y + 1] } },
              { from: { bond: [y + 1, z + 1] }, to: { atom: z + 1 } },
            ]);
          }
        }
      }
      // Move 2: π bond Y=Z shifts toward cation X (X–Y becomes π, Z becomes the cation).
      if (emptyP(orders, charges, x)) {
        for (const y of v.nbrs[x]) {
          for (const z of v.nbrs[y]) {
            if (z === x || el(z) !== 'C') continue;
            const yz = bondOf(y, z);
            if (orders[yz] !== 2) continue;
            const o = orders.slice();
            const c = charges.slice();
            o[bondOf(x, y)] += 1;
            o[yz] -= 1;
            c[x] -= 1;
            c[z] += 1;
            push(cur, o, c, [{ from: { bond: [y + 1, z + 1] }, to: { bond: [x + 1, y + 1] } }]);
          }
        }
      }
    }
    // Move 2b: a conjugated C=O polarizes onto oxygen (C⁺–O⁻), which lets the cation travel down the
    // π system — the textbook picture of why the β-carbon of an enone is electrophilic. Isolated
    // carbonyls are skipped so every ketone doesn't sprout a charge-separated form.
    if (cur === 0 || out[cur].charges.every((q, i) => q === base.charges[i])) {
      for (let y = 0; y < n; y++) {
        if (el(y) !== 'C' || charges[y] !== 0) continue;
        for (const z of v.nbrs[y]) {
          const yz = bondOf(y, z);
          if (el(z) !== 'O' || orders[yz] !== 2 || charges[z] !== 0) continue;
          const conjugated = v.nbrs[y].some((w) => w !== z && el(w) === 'C' && v.nbrBonds[w].some((b) => orders[b] === 2 && b !== bondOf(w, y)));
          if (!conjugated) continue;
          const o = orders.slice();
          const c = charges.slice();
          o[yz] -= 1;
          c[y] += 1;
          c[z] -= 1;
          push(cur, o, c, [{ from: { bond: [y + 1, z + 1] }, to: { atom: z + 1 } }]);
        }
      }
    }
    // Move 3: Kekulé shift around a six-ring of alternating single/double bonds.
    for (const ring of rings) {
      const bonds = ring.map((a, k) => bondOf(a, ring[(k + 1) % ring.length]));
      if (bonds.some((b) => b < 0)) continue;
      const pattern = bonds.map((b) => orders[b]);
      const alt = pattern.every((o, k) => (o === 2) === (k % 2 === 0)) || pattern.every((o, k) => (o === 2) === (k % 2 === 1));
      if (!alt) continue;
      const o = orders.slice();
      for (const b of bonds) o[b] = orders[b] === 2 ? 1 : 2;
      const arrows: ResArrow[] = [];
      bonds.forEach((b, k) => {
        if (orders[b] !== 2) return;
        const a1 = ring[(k + 1) % 6];
        const a2 = ring[(k + 2) % 6];
        arrows.push({ from: { bond: [ring[k] + 1, a1 + 1] }, to: { bond: [a1 + 1, a2 + 1] } });
      });
      push(cur, o, charges.slice(), arrows);
    }
  }

  // Weights: missing octets and charge placement dominate, then the number of charges.
  const scored: Contributor[] = out.map((c) => {
    let score = 0;
    const notes: string[] = [];
    let charged = 0;
    for (let i = 0; i < n; i++) {
      const q = c.charges[i];
      if (q !== 0) charged++;
      if (VALENCE_E[el(i)] !== undefined && el(i) !== 'B' && electrons(c.orders, c.charges, i) < 8 && (q !== 0 || lonePairs(c.orders, c.charges, i) === 0) && sumOrders(c.orders, i) + H[i] < 4 && el(i) !== 'S') {
        score += 4;
        notes.push(`${el(i)} has only a sextet (no octet)`);
      }
      if (q < 0 && EN[el(i)] !== undefined && EN[el(i)] < 3) {
        score += 1.5;
        notes.push(`negative charge on ${el(i) === 'C' ? 'carbon' : el(i)}, not the more electronegative atom`);
      }
      if (q > 0 && el(i) === 'O') {
        score += 1;
        notes.push('positive charge on oxygen');
      }
    }
    const baseCharged = base.charges.filter((q) => q !== 0).length;
    score += charged * 1.2;
    if (charged > baseCharged) notes.push('more charge separation');
    return { ...c, score, weight: 'minor', notes: [...new Set(notes)] };
  });
  const best = Math.min(...scored.map((c) => c.score));
  for (const c of scored) c.weight = c.score - best < 0.5 ? 'major' : 'minor';

  const delocalized = new Set<number>();
  const delocalizedBonds = new Set<number>();
  for (const c of scored) {
    c.charges.forEach((q, i) => q !== base.charges[i] && delocalized.add(i));
    c.orders.forEach((o, b) => {
      if (o !== base.orders[b]) {
        delocalizedBonds.add(b);
        delocalized.add(v.index.get(doc.bonds[b].a1)!);
        delocalized.add(v.index.get(doc.bonds[b].a2)!);
      }
    });
  }
  return {
    contributors: scored,
    equivalent: scored.length > 1 && scored.every((c) => c.weight === 'major'),
    delocalized: [...delocalized],
    delocalizedBonds: [...delocalizedBonds],
  };
}

/** Apply a contributor's electrons to a copy of the document (H counts pinned so they never shift). */
export function contributorDocument<T extends Pick<MoleculeDocument, 'atoms' | 'bonds'>>(doc: T, c: Contributor): T {
  const v = new MolView(doc);
  return {
    ...doc,
    atoms: doc.atoms.map((a, i) => ({ ...a, formalCharge: c.charges[i], explicitHydrogens: v.totalH(i) })),
    bonds: doc.bonds.map((b, k) => ({ ...b, order: c.orders[k] as 1 | 2 | 3 })),
  };
}
