'use client';
import type { Provenance } from '@/lib/types';
import { I } from '../ui/icons';

export const PROVENANCE: Record<Provenance, { label: string; long: string; tone: string }> = {
  verified_systematic: { label: 'Verified', long: 'Verified systematic name: generated by the course-rule engine and round-trip checked (name → OPSIN → same InChIKey, stereo included).', tone: 'bg-accent text-accent-ink' },
  database_name: { label: 'Database name', long: 'Exact InChIKey match in PubChem; its recorded IUPAC name (Lexichem-generated).', tone: 'bg-[#1c7ed6]/85 text-white' },
  accepted_common: { label: 'Common name', long: 'Accepted common name from a curated source (PubChem synonyms or the course list).', tone: 'bg-panel-raised text-text border border-border-strong' },
  course_convention: { label: 'Course convention', long: 'Accepted under a course naming profile (older rules or common prefixes); verified by structure.', tone: 'bg-panel-raised text-text border border-border-strong' },
  candidate_verified: { label: 'Candidate · verified by structure', long: 'Machine-generated name that parses back (OPSIN) to exactly this structure, stereo included.', tone: 'bg-amber text-[#1a1406]' },
  unverified_candidate: { label: 'Unverified', long: 'A name that could not be round-trip verified. Never used as the answer or for grading.', tone: 'bg-danger-soft text-danger border border-danger/40' },
  pending: { label: 'Verifying…', long: 'Checking the name by parsing it back to a structure.', tone: 'bg-panel-raised text-text-2 border border-border' },
  offline: { label: 'Not yet verified', long: 'Offline: this name comes from the course engine and has not been round-trip verified yet.', tone: 'bg-panel-raised text-text-2 border border-dashed border-border-strong' },
  unsupported: { label: 'No verified name', long: 'Outside the verified scope — see the honest coverage message.', tone: 'bg-panel-raised text-text-2 border border-border' },
};

const MINI: Partial<Record<Provenance, string>> = {
  database_name: 'DB', accepted_common: 'Common', course_convention: 'Course', unverified_candidate: '!', offline: 'Offline', unsupported: '—',
};

/** `mini` is the phone-width form: an icon or a two-word label, with the full label for screen readers. */
export function ProvenanceBadge({ p, compact, mini }: { p: Provenance; compact?: boolean; mini?: boolean }) {
  const info = PROVENANCE[p];
  return (
    <span
      title={info.long}
      aria-label={mini ? info.label : undefined}
      className={`inline-flex shrink-0 items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold ${info.tone}`}
      data-provenance={p}
    >
      {(p === 'verified_systematic' || (mini && p === 'candidate_verified')) && <I.Check size={12} strokeWidth={2.6} />}
      {p === 'pending' && <span className="h-2 w-2 animate-pulse rounded-full bg-current" />}
      {mini ? MINI[p] : !compact ? info.label : p !== 'verified_systematic' ? info.label : null}
    </span>
  );
}
